FROM alpine:3.22 AS build
RUN apk add --no-cache build-base cmake curl gcc git linux-headers patch perl python3
COPY ./  /iotivity-lite/
WORKDIR /iotivity-lite
RUN git submodule update --recursive
RUN mkdir /iotivity-lite/build
WORKDIR /iotivity-lite/build
RUN	cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_VERBOSE_MAKEFILE=ON \
	-DOC_DEBUG_ENABLED=1 -DOC_TCP_ENABLED=1 -DOC_IPV4_ENABLED=1 -DOC_CLOUD_ENABLED=1 -DOC_OSCORE_ENABLED=0 -DOC_SECURITY_ENABLED=1 -DOC_PKI_ENABLED=1 .. && \
	cmake --build . --target cloud_server

FROM alpine:3.22 AS service
RUN apk add --no-cache bash
COPY --from=build /iotivity-lite/build/apps/cloud_server /usr/local/bin/cloud_server
COPY --from=build /iotivity-lite/build/apps/cloud_server_creds /opt/cloud_server/cloud_server_creds
COPY --from=build /iotivity-lite/build/apps/pki_certs /opt/cloud_server/pki_certs
WORKDIR /opt/cloud_server
CMD ["/usr/local/bin/cloud_server"]
