# This is a basic workflow to help you get started with Actions

name: CI-android

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   make_android:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE,  so your job can access it
      - uses: actions/checkout@v2
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21e

      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: android make secured
        run: |
          # debugging info
          env
          ls -l
          # setup of the java (swig) environment
          #sudo apt-get -y install make autoconf swig default-jdk
          #sudo apt-get -y default-jdk
          swig -version
          java -version
          javac -version
          wget --quiet --output-document=junit-4.13.jar https://search.maven.org/remotecontent?filepath=junit/junit/4.13/junit-4.13.jar
          wget --quiet --output-document=hamcrest-core-1.3.jar https://search.maven.org/remotecontent?filepath=org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
          #ndk-build NDK_DEBUG=1
          # actual build
          ls -l ${{ env.ANDROID_NDK_HOME }}
          #
          ls -l ${{ env.ANDROID_SDK_ROOT }}
          
          #ANDROID_NDK_ROOT
          ls -l ${{ env.ANDROID_NDK_ROOT }}
          ls -lR /usr/local/lib/android/
          
          cd port/android
          make DYNAMIC=1 TCP=1 IPV4=1 SECURE=1 PKI=1 CLOUD=1 JAVA=1 DEBUG=0
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
          ANDROID_HOME: ${{ env.ANDROID_NDK_LATEST_HOME }}
          NDK_HOME: ${{ env.ANDROID_NDK_LATEST_HOME }}
          